# examples/0001-small-network.toml
[relaychain]
default_image = "docker.io/parity/polkadot:latest"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  ws_port = 9944

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  ws_port = 9922

[[parachains]]
chain= "acala"
id = 100

  [parachains.collator]
  name = "alice"
  image = "docker.io/parity/polkadot-parachain:latest"
  command = "polkadot-parachain"
  args = ["-lparachain=debug"]
